# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20160611_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
