# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_homepage', models.BooleanField(help_text='Click here if you want this page to be the current home page')),
                ('homepage_name', models.CharField(max_length=35)),
                ('heading', models.CharField(default='Central New York LAN', help_text='The main heading for the homepage', max_length=200)),
                ('subheading', models.CharField(default='Default subheading', help_text='The subheading just below the heading', max_length=200)),
                ('banner_image', models.ImageField(blank=True, help_text='Banner Image', null=True, upload_to=pages.models.upload_location)),
                ('first_content_heading', models.CharField(default='First content heading under banner', help_text='First content heading under banner', max_length=200)),
                ('first_image', models.ImageField(blank=True, help_text='First Content Heading Image', null=True, upload_to=pages.models.upload_location)),
                ('second_content_heading', models.CharField(default='Default Second Content Heading', help_text='Second content heading under banner', max_length=200)),
                ('second_image', models.ImageField(blank=True, help_text='Second Content Heading Image', null=True, upload_to=pages.models.upload_location)),
                ('third_content_heading', models.CharField(default='Default Third Content Heading', help_text='Third content heading under banner', max_length=200)),
                ('third_image', models.ImageField(blank=True, help_text='Third Content Heading Image', null=True, upload_to=pages.models.upload_location)),
            ],
            options={
                'verbose_name': 'Home page',
                'verbose_name_plural': 'Home pages',
            },
        ),
    ]
