# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(help_text='Enter what you want to say about CNY LAN. This will show up at the top of the about page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
