# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About page', 'verbose_name_plural': 'About pages'},
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
    ]
