# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20160609_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='first_content_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='second_content_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subheading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='third_content_heading',
        ),
    ]
