# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_delete_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Homepage', 'verbose_name_plural': 'Homepages'},
        ),
    ]
