# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20160614_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='heading',
            field=models.CharField(default='Default Heading', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subheading',
            field=models.CharField(default='Default Subheading', max_length=100),
        ),
    ]
