# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import lanapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0004_auto_20160606_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='game',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, help_text='Image field for game', null=True, upload_to=lanapp.models.upload_location),
        ),
    ]
