# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0011_prize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prize',
            old_name='link',
            new_name='url',
        ),
    ]
