# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0015_auto_20160608_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=35),
        ),
    ]
