# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0016_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pay_button_text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
