# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('event_start_date', models.DateTimeField(verbose_name='event start date')),
                ('event_end_date', models.DateTimeField(verbose_name='event end date')),
                ('venue', models.CharField(max_length=75)),
                ('street_address', models.CharField(max_length=75)),
                ('city', models.CharField(default='Rome', max_length=75)),
                ('state', models.CharField(default='New York', max_length=75)),
                ('zip_code', models.CharField(default='13440', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('genre', models.CharField(max_length=100)),
                ('gaming_system', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='games',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lanapp.Game'),
        ),
    ]
