# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0003_auto_20160606_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='game',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
