# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import lanapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0005_auto_20160606_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('image', models.ImageField(blank=True, help_text='Image field for a sponsor', null=True, upload_to=lanapp.models.upload_location)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='lanapp.Sponsor'),
        ),
    ]
