# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0007_auto_20160606_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logistics_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
