# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0008_event_logistics_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='logistics_description',
            new_name='logistics_information',
        ),
    ]
