# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lanapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0010_auto_20160606_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('image', models.ImageField(blank=True, help_text='Image field for a prize', null=True, upload_to=lanapp.models.upload_location)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lanapp.Event')),
            ],
        ),
    ]
