# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0012_auto_20160606_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='website',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='website',
        ),
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prize',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
