# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import lanapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0013_auto_20160606_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image associated with this event', null=True, upload_to=lanapp.models.upload_location),
        ),
    ]
