# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0014_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='event',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='event',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='games',
            field=models.ManyToManyField(blank=True, to='lanapp.Game'),
        ),
        migrations.AddField(
            model_name='event',
            name='prizes',
            field=models.ManyToManyField(blank=True, to='lanapp.Prize'),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='lanapp.Sponsor'),
        ),
    ]
