# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0017_event_pay_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='Pay here with Paypal', max_length=100),
        ),
    ]
